// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: extension.proto

package extension

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	defs "qst-ext-appsearcher-go/pb/defs"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisplayItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjId uint32  `protobuf:"varint,1,opt,name=obj_id,json=objId,proto3" json:"obj_id,omitempty"`
	Name  string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hint  *string `protobuf:"bytes,3,opt,name=hint,proto3,oneof" json:"hint,omitempty"`
}

func (x *DisplayItem) Reset() {
	*x = DisplayItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisplayItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayItem) ProtoMessage() {}

func (x *DisplayItem) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayItem.ProtoReflect.Descriptor instead.
func (*DisplayItem) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{0}
}

func (x *DisplayItem) GetObjId() uint32 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *DisplayItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DisplayItem) GetHint() string {
	if x != nil && x.Hint != nil {
		return *x.Hint
	}
	return ""
}

type DisplayList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*DisplayItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *DisplayList) Reset() {
	*x = DisplayList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisplayList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayList) ProtoMessage() {}

func (x *DisplayList) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayList.ProtoReflect.Descriptor instead.
func (*DisplayList) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{1}
}

func (x *DisplayList) GetList() []*DisplayItem {
	if x != nil {
		return x.List
	}
	return nil
}

type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Input) Reset() {
	*x = Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{2}
}

func (x *Input) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SearchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Mresult:
	//
	//	*SearchResult_Status
	//	*SearchResult_Ok
	Mresult isSearchResult_Mresult `protobuf_oneof:"mresult"`
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{3}
}

func (m *SearchResult) GetMresult() isSearchResult_Mresult {
	if m != nil {
		return m.Mresult
	}
	return nil
}

func (x *SearchResult) GetStatus() *defs.Status {
	if x, ok := x.GetMresult().(*SearchResult_Status); ok {
		return x.Status
	}
	return nil
}

func (x *SearchResult) GetOk() *SearchResult_MOk {
	if x, ok := x.GetMresult().(*SearchResult_Ok); ok {
		return x.Ok
	}
	return nil
}

type isSearchResult_Mresult interface {
	isSearchResult_Mresult()
}

type SearchResult_Status struct {
	Status *defs.Status `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type SearchResult_Ok struct {
	Ok *SearchResult_MOk `protobuf:"bytes,2,opt,name=ok,proto3,oneof"`
}

func (*SearchResult_Status) isSearchResult_Mresult() {}

func (*SearchResult_Ok) isSearchResult_Mresult() {}

type SubmitHint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjId uint32  `protobuf:"varint,1,opt,name=obj_id,json=objId,proto3" json:"obj_id,omitempty"`
	Hint  *string `protobuf:"bytes,3,opt,name=hint,proto3,oneof" json:"hint,omitempty"`
}

func (x *SubmitHint) Reset() {
	*x = SubmitHint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitHint) ProtoMessage() {}

func (x *SubmitHint) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitHint.ProtoReflect.Descriptor instead.
func (*SubmitHint) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitHint) GetObjId() uint32 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *SubmitHint) GetHint() string {
	if x != nil && x.Hint != nil {
		return *x.Hint
	}
	return ""
}

type FillHint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjId uint32 `protobuf:"varint,1,opt,name=obj_id,json=objId,proto3" json:"obj_id,omitempty"`
}

func (x *FillHint) Reset() {
	*x = FillHint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FillHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillHint) ProtoMessage() {}

func (x *FillHint) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillHint.ProtoReflect.Descriptor instead.
func (*FillHint) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{5}
}

func (x *FillHint) GetObjId() uint32 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

type FillResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Mresult:
	//
	//	*FillResult_Status
	//	*FillResult_Ok
	Mresult isFillResult_Mresult `protobuf_oneof:"mresult"`
}

func (x *FillResult) Reset() {
	*x = FillResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FillResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillResult) ProtoMessage() {}

func (x *FillResult) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillResult.ProtoReflect.Descriptor instead.
func (*FillResult) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{6}
}

func (m *FillResult) GetMresult() isFillResult_Mresult {
	if m != nil {
		return m.Mresult
	}
	return nil
}

func (x *FillResult) GetStatus() *defs.Status {
	if x, ok := x.GetMresult().(*FillResult_Status); ok {
		return x.Status
	}
	return nil
}

func (x *FillResult) GetOk() *FillResult_MOk {
	if x, ok := x.GetMresult().(*FillResult_Ok); ok {
		return x.Ok
	}
	return nil
}

type isFillResult_Mresult interface {
	isFillResult_Mresult()
}

type FillResult_Status struct {
	Status *defs.Status `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type FillResult_Ok struct {
	Ok *FillResult_MOk `protobuf:"bytes,2,opt,name=ok,proto3,oneof"`
}

func (*FillResult_Status) isFillResult_Mresult() {}

func (*FillResult_Ok) isFillResult_Mresult() {}

type SearchResult_MOk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DisplayList *DisplayList `protobuf:"bytes,2,opt,name=display_list,json=displayList,proto3" json:"display_list,omitempty"`
}

func (x *SearchResult_MOk) Reset() {
	*x = SearchResult_MOk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResult_MOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult_MOk) ProtoMessage() {}

func (x *SearchResult_MOk) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult_MOk.ProtoReflect.Descriptor instead.
func (*SearchResult_MOk) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SearchResult_MOk) GetDisplayList() *DisplayList {
	if x != nil {
		return x.DisplayList
	}
	return nil
}

type FillResult_MOk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DisplayList *DisplayList `protobuf:"bytes,2,opt,name=display_list,json=displayList,proto3" json:"display_list,omitempty"`
}

func (x *FillResult_MOk) Reset() {
	*x = FillResult_MOk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FillResult_MOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillResult_MOk) ProtoMessage() {}

func (x *FillResult_MOk) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillResult_MOk.ProtoReflect.Descriptor instead.
func (*FillResult_MOk) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{6, 0}
}

func (x *FillResult_MOk) GetDisplayList() *DisplayList {
	if x != nil {
		return x.DisplayList
	}
	return nil
}

var File_extension_proto protoreflect.FileDescriptor

var file_extension_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x65, 0x78, 0x74, 0x1a, 0x0a, 0x64, 0x65, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x6f, 0x62, 0x6a, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x04,
	0x68, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x68, 0x69,
	0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x68, 0x69, 0x6e, 0x74, 0x22, 0x33,
	0x0a, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x78,
	0x74, 0x2e, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0x21, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xa6, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x65, 0x66, 0x73, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x27, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x78,
	0x74, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x4d,
	0x4f, 0x6b, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x6b, 0x1a, 0x3a, 0x0a, 0x03, 0x4d, 0x4f, 0x6b, 0x12,
	0x33, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x78, 0x74, 0x2e, 0x44, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x45, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x48, 0x69, 0x6e, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x6f, 0x62, 0x6a, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f,
	0x62, 0x6a, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x68, 0x69, 0x6e, 0x74, 0x22, 0x21, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x6c, 0x48, 0x69,
	0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6f, 0x62, 0x6a, 0x49, 0x64, 0x22, 0xa2, 0x01, 0x0a, 0x0a, 0x46, 0x69,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x65, 0x66, 0x73, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x25, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x65,
	0x78, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x4d, 0x4f,
	0x6b, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x6b, 0x1a, 0x3a, 0x0a, 0x03, 0x4d, 0x4f, 0x6b, 0x12, 0x33,
	0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x78, 0x74, 0x2e, 0x44, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x64,
	0x0a, 0x0b, 0x45, 0x78, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x12, 0x29, 0x0a,
	0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x0a, 0x2e, 0x65, 0x78, 0x74, 0x2e, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x1a, 0x11, 0x2e, 0x65, 0x78, 0x74, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x06, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x12, 0x0f, 0x2e, 0x65, 0x78, 0x74, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x48,
	0x69, 0x6e, 0x74, 0x1a, 0x0d, 0x2e, 0x64, 0x65, 0x66, 0x73, 0x2e, 0x4d, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23, 0x71, 0x73, 0x74, 0x2d, 0x65, 0x78, 0x74, 0x2d,
	0x61, 0x70, 0x70, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x70,
	0x62, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_extension_proto_rawDescOnce sync.Once
	file_extension_proto_rawDescData = file_extension_proto_rawDesc
)

func file_extension_proto_rawDescGZIP() []byte {
	file_extension_proto_rawDescOnce.Do(func() {
		file_extension_proto_rawDescData = protoimpl.X.CompressGZIP(file_extension_proto_rawDescData)
	})
	return file_extension_proto_rawDescData
}

var file_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_extension_proto_goTypes = []interface{}{
	(*DisplayItem)(nil),      // 0: ext.DisplayItem
	(*DisplayList)(nil),      // 1: ext.DisplayList
	(*Input)(nil),            // 2: ext.Input
	(*SearchResult)(nil),     // 3: ext.SearchResult
	(*SubmitHint)(nil),       // 4: ext.SubmitHint
	(*FillHint)(nil),         // 5: ext.FillHint
	(*FillResult)(nil),       // 6: ext.FillResult
	(*SearchResult_MOk)(nil), // 7: ext.SearchResult.MOk
	(*FillResult_MOk)(nil),   // 8: ext.FillResult.MOk
	(*defs.Status)(nil),      // 9: defs.Status
	(*defs.MResult)(nil),     // 10: defs.MResult
}
var file_extension_proto_depIdxs = []int32{
	0,  // 0: ext.DisplayList.list:type_name -> ext.DisplayItem
	9,  // 1: ext.SearchResult.status:type_name -> defs.Status
	7,  // 2: ext.SearchResult.ok:type_name -> ext.SearchResult.MOk
	9,  // 3: ext.FillResult.status:type_name -> defs.Status
	8,  // 4: ext.FillResult.ok:type_name -> ext.FillResult.MOk
	1,  // 5: ext.SearchResult.MOk.display_list:type_name -> ext.DisplayList
	1,  // 6: ext.FillResult.MOk.display_list:type_name -> ext.DisplayList
	2,  // 7: ext.ExtInteract.Search:input_type -> ext.Input
	4,  // 8: ext.ExtInteract.Submit:input_type -> ext.SubmitHint
	3,  // 9: ext.ExtInteract.Search:output_type -> ext.SearchResult
	10, // 10: ext.ExtInteract.Submit:output_type -> defs.MResult
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_extension_proto_init() }
func file_extension_proto_init() {
	if File_extension_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_extension_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisplayItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisplayList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitHint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FillHint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FillResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResult_MOk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FillResult_MOk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_extension_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_extension_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*SearchResult_Status)(nil),
		(*SearchResult_Ok)(nil),
	}
	file_extension_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_extension_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*FillResult_Status)(nil),
		(*FillResult_Ok)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extension_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extension_proto_goTypes,
		DependencyIndexes: file_extension_proto_depIdxs,
		MessageInfos:      file_extension_proto_msgTypes,
	}.Build()
	File_extension_proto = out.File
	file_extension_proto_rawDesc = nil
	file_extension_proto_goTypes = nil
	file_extension_proto_depIdxs = nil
}
