// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: daemon.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	defs "qst-ext-appsearcher-go/pb/defs"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Prompt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Prompt) Reset() {
	*x = Prompt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prompt) ProtoMessage() {}

func (x *Prompt) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prompt.ProtoReflect.Descriptor instead.
func (*Prompt) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *Prompt) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ExtAddrResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Mresult:
	//
	//	*ExtAddrResult_Status
	//	*ExtAddrResult_Ok
	Mresult isExtAddrResult_Mresult `protobuf_oneof:"mresult"`
}

func (x *ExtAddrResult) Reset() {
	*x = ExtAddrResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtAddrResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtAddrResult) ProtoMessage() {}

func (x *ExtAddrResult) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtAddrResult.ProtoReflect.Descriptor instead.
func (*ExtAddrResult) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{1}
}

func (m *ExtAddrResult) GetMresult() isExtAddrResult_Mresult {
	if m != nil {
		return m.Mresult
	}
	return nil
}

func (x *ExtAddrResult) GetStatus() *defs.Status {
	if x, ok := x.GetMresult().(*ExtAddrResult_Status); ok {
		return x.Status
	}
	return nil
}

func (x *ExtAddrResult) GetOk() *ExtAddrResult_MOk {
	if x, ok := x.GetMresult().(*ExtAddrResult_Ok); ok {
		return x.Ok
	}
	return nil
}

type isExtAddrResult_Mresult interface {
	isExtAddrResult_Mresult()
}

type ExtAddrResult_Status struct {
	Status *defs.Status `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type ExtAddrResult_Ok struct {
	Ok *ExtAddrResult_MOk `protobuf:"bytes,2,opt,name=ok,proto3,oneof"`
}

func (*ExtAddrResult_Status) isExtAddrResult_Mresult() {}

func (*ExtAddrResult_Ok) isExtAddrResult_Mresult() {}

type ExtInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Dir    string `protobuf:"bytes,4,opt,name=dir,proto3" json:"dir,omitempty"`
	Exec   string `protobuf:"bytes,5,opt,name=exec,proto3" json:"exec,omitempty"`
}

func (x *ExtInfo) Reset() {
	*x = ExtInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtInfo) ProtoMessage() {}

func (x *ExtInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtInfo.ProtoReflect.Descriptor instead.
func (*ExtInfo) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *ExtInfo) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ExtInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtInfo) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *ExtInfo) GetExec() string {
	if x != nil {
		return x.Exec
	}
	return ""
}

type ConfigHint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//	enum Type {
	//	  CREATE = 0;
	//	  UPDATE = 1;
	//	  DELETE = 2;
	//	}
	//
	//	message ExtInfoForCreate {
	//	  string name = 1;
	//	  string prompt = 2;
	//	  string dir = 3;
	//	  string exec = 4;
	//	}
	//
	//	message Create {
	//	  repeated ExtInfoForCreate exts = 1;
	//	}
	//
	//	message ExtInfoForUpdate {
	//	  uint32 id = 1;
	//	  optional string name = 2;
	//	  optional string dir = 3;
	//	  optional string exec = 4;
	//	}
	//
	//	message Update {
	//	  repeated ExtInfoForUpdate exts = 1;
	//	}
	//
	//	message ExtInfoForDelete {
	//	  uint32 id = 1;
	//	}
	//
	//	message Delete {
	//	  repeated ExtInfoForDelete exts = 1;
	//	}
	//
	// optional map<string, ExtInfoForCreate> create = 1;
	// optional map<string, ExtInfoForUpdate> update = 2;
	// optional map<string, ExtInfoForDelete> delete = 3;
	Exts map[uint32]*ExtInfo `protobuf:"bytes,1,rep,name=exts,proto3" json:"exts,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ConfigHint) Reset() {
	*x = ConfigHint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigHint) ProtoMessage() {}

func (x *ConfigHint) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigHint.ProtoReflect.Descriptor instead.
func (*ConfigHint) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigHint) GetExts() map[uint32]*ExtInfo {
	if x != nil {
		return x.Exts
	}
	return nil
}

type ConfigResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Mresult:
	//
	//	*ConfigResult_Status
	//	*ConfigResult_Ok
	Mresult isConfigResult_Mresult `protobuf_oneof:"mresult"`
}

func (x *ConfigResult) Reset() {
	*x = ConfigResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResult) ProtoMessage() {}

func (x *ConfigResult) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResult.ProtoReflect.Descriptor instead.
func (*ConfigResult) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{4}
}

func (m *ConfigResult) GetMresult() isConfigResult_Mresult {
	if m != nil {
		return m.Mresult
	}
	return nil
}

func (x *ConfigResult) GetStatus() *defs.Status {
	if x, ok := x.GetMresult().(*ConfigResult_Status); ok {
		return x.Status
	}
	return nil
}

func (x *ConfigResult) GetOk() *ConfigResult_MOk {
	if x, ok := x.GetMresult().(*ConfigResult_Ok); ok {
		return x.Ok
	}
	return nil
}

type isConfigResult_Mresult interface {
	isConfigResult_Mresult()
}

type ConfigResult_Status struct {
	Status *defs.Status `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type ConfigResult_Ok struct {
	Ok *ConfigResult_MOk `protobuf:"bytes,2,opt,name=ok,proto3,oneof"`
}

func (*ConfigResult_Status) isConfigResult_Mresult() {}

func (*ConfigResult_Ok) isConfigResult_Mresult() {}

type SetUpResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Mresult:
	//
	//	*SetUpResult_Status
	//	*SetUpResult_Ok
	Mresult isSetUpResult_Mresult `protobuf_oneof:"mresult"`
}

func (x *SetUpResult) Reset() {
	*x = SetUpResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUpResult) ProtoMessage() {}

func (x *SetUpResult) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUpResult.ProtoReflect.Descriptor instead.
func (*SetUpResult) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{5}
}

func (m *SetUpResult) GetMresult() isSetUpResult_Mresult {
	if m != nil {
		return m.Mresult
	}
	return nil
}

func (x *SetUpResult) GetStatus() *defs.Status {
	if x, ok := x.GetMresult().(*SetUpResult_Status); ok {
		return x.Status
	}
	return nil
}

func (x *SetUpResult) GetOk() *SetUpResult_MOk {
	if x, ok := x.GetMresult().(*SetUpResult_Ok); ok {
		return x.Ok
	}
	return nil
}

type isSetUpResult_Mresult interface {
	isSetUpResult_Mresult()
}

type SetUpResult_Status struct {
	Status *defs.Status `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type SetUpResult_Ok struct {
	Ok *SetUpResult_MOk `protobuf:"bytes,2,opt,name=ok,proto3,oneof"`
}

func (*SetUpResult_Status) isSetUpResult_Mresult() {}

func (*SetUpResult_Ok) isSetUpResult_Mresult() {}

type ExtAddrResult_MOk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *ExtAddrResult_MOk) Reset() {
	*x = ExtAddrResult_MOk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtAddrResult_MOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtAddrResult_MOk) ProtoMessage() {}

func (x *ExtAddrResult_MOk) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtAddrResult_MOk.ProtoReflect.Descriptor instead.
func (*ExtAddrResult_MOk) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ExtAddrResult_MOk) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ConfigResult_MOk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exts map[uint32]*ExtInfo `protobuf:"bytes,2,rep,name=exts,proto3" json:"exts,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ConfigResult_MOk) Reset() {
	*x = ConfigResult_MOk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigResult_MOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResult_MOk) ProtoMessage() {}

func (x *ConfigResult_MOk) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResult_MOk.ProtoReflect.Descriptor instead.
func (*ConfigResult_MOk) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ConfigResult_MOk) GetExts() map[uint32]*ExtInfo {
	if x != nil {
		return x.Exts
	}
	return nil
}

type SetUpResult_MOk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Running map[string]string `protobuf:"bytes,1,rep,name=running,proto3" json:"running,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SetUpResult_MOk) Reset() {
	*x = SetUpResult_MOk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUpResult_MOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUpResult_MOk) ProtoMessage() {}

func (x *SetUpResult_MOk) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUpResult_MOk.ProtoReflect.Descriptor instead.
func (*SetUpResult_MOk) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SetUpResult_MOk) GetRunning() map[string]string {
	if x != nil {
		return x.Running
	}
	return nil
}

var File_daemon_proto protoreflect.FileDescriptor

var file_daemon_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x1a, 0x0a, 0x64, 0x65, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x22, 0x0a, 0x06, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x8a, 0x01, 0x0a, 0x0d, 0x45, 0x78, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x65, 0x66, 0x73, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x2b, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64,
	0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x78, 0x74, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x2e, 0x4d, 0x4f, 0x6b, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x6b, 0x1a, 0x19, 0x0a,
	0x03, 0x4d, 0x4f, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x5b, 0x0a, 0x07, 0x45, 0x78, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x65, 0x78, 0x65, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x78, 0x65, 0x63,
	0x22, 0x88, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x69, 0x6e, 0x74, 0x12,
	0x30, 0x0a, 0x04, 0x65, 0x78, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x69, 0x6e,
	0x74, 0x2e, 0x45, 0x78, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x65, 0x78, 0x74,
	0x73, 0x1a, 0x48, 0x0a, 0x09, 0x45, 0x78, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x78, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xf7, 0x01, 0x0a, 0x0c,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64,
	0x65, 0x66, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x2a, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x4d, 0x4f, 0x6b, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x6b,
	0x1a, 0x87, 0x01, 0x0a, 0x03, 0x4d, 0x4f, 0x6b, 0x12, 0x36, 0x0a, 0x04, 0x65, 0x78, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x4d, 0x4f, 0x6b,
	0x2e, 0x45, 0x78, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x65, 0x78, 0x74, 0x73,
	0x1a, 0x48, 0x0a, 0x09, 0x45, 0x78, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x78, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xef, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x55, 0x70, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x65, 0x66, 0x73, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a,
	0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x61, 0x65, 0x6d,
	0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x4d,
	0x4f, 0x6b, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x6b, 0x1a, 0x81, 0x01, 0x0a, 0x03, 0x4d, 0x4f, 0x6b,
	0x12, 0x3e, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x70,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x4d, 0x4f, 0x6b, 0x2e, 0x52, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x1a, 0x3a, 0x0a, 0x0c, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x09, 0x0a, 0x07,
	0x6d, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xd6, 0x01, 0x0a, 0x0c, 0x4d, 0x61, 0x69, 0x6e,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x53, 0x65, 0x74, 0x55,
	0x70, 0x12, 0x0b, 0x2e, 0x64, 0x65, 0x66, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13,
	0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x70, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x0b, 0x2e, 0x64, 0x65, 0x66, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x14, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x48, 0x69, 0x6e, 0x74, 0x1a, 0x0d, 0x2e, 0x64, 0x65, 0x66, 0x73, 0x2e,
	0x4d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x45, 0x78, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x0e, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x1a, 0x15, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x45, 0x78, 0x74, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x42, 0x22, 0x5a, 0x20, 0x71, 0x73, 0x74, 0x2d, 0x65, 0x78, 0x74, 0x2d, 0x61, 0x70, 0x70, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_daemon_proto_rawDescOnce sync.Once
	file_daemon_proto_rawDescData = file_daemon_proto_rawDesc
)

func file_daemon_proto_rawDescGZIP() []byte {
	file_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_daemon_proto_rawDescData)
	})
	return file_daemon_proto_rawDescData
}

var file_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_daemon_proto_goTypes = []interface{}{
	(*Prompt)(nil),            // 0: daemon.Prompt
	(*ExtAddrResult)(nil),     // 1: daemon.ExtAddrResult
	(*ExtInfo)(nil),           // 2: daemon.ExtInfo
	(*ConfigHint)(nil),        // 3: daemon.ConfigHint
	(*ConfigResult)(nil),      // 4: daemon.ConfigResult
	(*SetUpResult)(nil),       // 5: daemon.SetUpResult
	(*ExtAddrResult_MOk)(nil), // 6: daemon.ExtAddrResult.MOk
	nil,                       // 7: daemon.ConfigHint.ExtsEntry
	(*ConfigResult_MOk)(nil),  // 8: daemon.ConfigResult.MOk
	nil,                       // 9: daemon.ConfigResult.MOk.ExtsEntry
	(*SetUpResult_MOk)(nil),   // 10: daemon.SetUpResult.MOk
	nil,                       // 11: daemon.SetUpResult.MOk.RunningEntry
	(*defs.Status)(nil),       // 12: defs.Status
	(*defs.Empty)(nil),        // 13: defs.Empty
	(*defs.MResult)(nil),      // 14: defs.MResult
}
var file_daemon_proto_depIdxs = []int32{
	12, // 0: daemon.ExtAddrResult.status:type_name -> defs.Status
	6,  // 1: daemon.ExtAddrResult.ok:type_name -> daemon.ExtAddrResult.MOk
	7,  // 2: daemon.ConfigHint.exts:type_name -> daemon.ConfigHint.ExtsEntry
	12, // 3: daemon.ConfigResult.status:type_name -> defs.Status
	8,  // 4: daemon.ConfigResult.ok:type_name -> daemon.ConfigResult.MOk
	12, // 5: daemon.SetUpResult.status:type_name -> defs.Status
	10, // 6: daemon.SetUpResult.ok:type_name -> daemon.SetUpResult.MOk
	2,  // 7: daemon.ConfigHint.ExtsEntry.value:type_name -> daemon.ExtInfo
	9,  // 8: daemon.ConfigResult.MOk.exts:type_name -> daemon.ConfigResult.MOk.ExtsEntry
	2,  // 9: daemon.ConfigResult.MOk.ExtsEntry.value:type_name -> daemon.ExtInfo
	11, // 10: daemon.SetUpResult.MOk.running:type_name -> daemon.SetUpResult.MOk.RunningEntry
	13, // 11: daemon.MainInteract.SetUp:input_type -> defs.Empty
	13, // 12: daemon.MainInteract.GetConfig:input_type -> defs.Empty
	3,  // 13: daemon.MainInteract.SetConfig:input_type -> daemon.ConfigHint
	0,  // 14: daemon.MainInteract.GetExtAddr:input_type -> daemon.Prompt
	5,  // 15: daemon.MainInteract.SetUp:output_type -> daemon.SetUpResult
	4,  // 16: daemon.MainInteract.GetConfig:output_type -> daemon.ConfigResult
	14, // 17: daemon.MainInteract.SetConfig:output_type -> defs.MResult
	1,  // 18: daemon.MainInteract.GetExtAddr:output_type -> daemon.ExtAddrResult
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_daemon_proto_init() }
func file_daemon_proto_init() {
	if File_daemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_daemon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prompt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtAddrResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigHint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUpResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtAddrResult_MOk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigResult_MOk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUpResult_MOk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_daemon_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ExtAddrResult_Status)(nil),
		(*ExtAddrResult_Ok)(nil),
	}
	file_daemon_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*ConfigResult_Status)(nil),
		(*ConfigResult_Ok)(nil),
	}
	file_daemon_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*SetUpResult_Status)(nil),
		(*SetUpResult_Ok)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_daemon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_proto_depIdxs,
		MessageInfos:      file_daemon_proto_msgTypes,
	}.Build()
	File_daemon_proto = out.File
	file_daemon_proto_rawDesc = nil
	file_daemon_proto_goTypes = nil
	file_daemon_proto_depIdxs = nil
}
